Vatuu/silent-hill-decomp

Makefile
README.md
include/bodyprog/bodyprog.h
include/main/fsqueue.h
include/main/rng.h
include/screens/b_konami/b_konami.h
include/screens/credits/credits.h
include/screens/options/options.h
include/screens/saveload/saveload.h
src/main/rng.c
src/screens/b_konami/b_konami.c
src/screens/credits/credits.c
src/screens/options/options.c
src/screens/saveload/saveload.c

- Adds matches for simple functions in `screens` overlays from the group effort on decomp.me.
- Minor fix for `Rng_Rand16` return type.
- README housekeeping.
Please do a squash merge instead of a regular one.

Simple matches

---

configs/sym.bodyprog.txt
include/bodyprog/math.h
include/bodyprog/vw_system.h
src/bodyprog/view/vc_main.c
src/bodyprog/view/vc_util.c
src/bodyprog/view/vw_calc.c
src/bodyprog/view/vw_main.c

Some easy matches from m2c, and fixed up some symbol types, mainly just to get vw_system.h included.
Not sure about the func_80096C94 / func_80096E78 funcs in math.h, my DB has them both named the same vwRotMatrixYXZ name, guess one is a different order but not really sure which.

bodyprog: add 28 vw matches

---

.clang-format
include/bodyprog/libsd.h
include/bodyprog/vw_system.h
src/bodyprog/libsd/sdmain.c
src/bodyprog/libsd/sdmidi.c
src/bodyprog/libsd/sdmidi2.c
src/bodyprog/libsd/ssmain.c
src/bodyprog/view/vc_main.c
src/bodyprog/view/vc_util.c
src/bodyprog/view/vw_calc.c
src/bodyprog/view/vw_main.c

Adds a few easy libsd matches, these mostly seem the same as libsnd funcs so wasn't sure if they were worth documenting separately, maybe if differences are found between them.
Updated clang-format to Allman, can use `git clang-format` to format any staged files for you, and ran that over view files.
There was an issue with clang-format wrapping `INCLUDE_ASM` to new lines too, which made splat put func into matchings folder & break the build, but adding it to `WhitespaceSensitiveMacros` seemed to fix that.

Add libsd matches, update clang-format, reformat view files

---

configs/sym.bodyprog.txt
diff_settings.py
include/bodyprog/math.h
include/bodyprog/vw_system.h
include/common.h
include/game.h
include/gpu.h
src/bodyprog/bodyprog_8004A87C.c
src/bodyprog/view/vc_main.c
src/bodyprog/view/vc_util.c
src/bodyprog/view/vw_calc.c
src/bodyprog/view/vw_main.c
src/stream/stream.c
tools/decompile.py

Adds most of the view/stream matches on decomp.me
```
$ python3 -m mapfile_parser progress build/out/VIN/STREAM.BIN.map asm/stream/ asm/stream/nonmatchings/ -i 3
stream.c.o                  :         2696 /     3704    72.7862%  ( 42.2836% /  58.0928%)
$ python3 -m mapfile_parser progress build/out/1ST/BODYPROG.BIN.map asm/bodyprog/ asm/bodyprog/nonmatchings/
bodyprog                    :        73976 /   501608    14.7478%  ( 14.7478% / 100.0000%)
```
stream would be almost 100% if this func could match: https://decomp.me/scratch/b3QWM, tried a bunch of changes and haven't had any luck yet though :/
Added kinda hacky fixes to decompile.py & diff_setting.py to get asm-differ at least start working, came in useful to get the scratches merged properly, needs some more work to let it …

Add `view` and `stream` matches, start s_GameWork/s_SysWork

---

.clang-format
configs/sym.bodyprog.txt
include/bodyprog/bodyprog.h
include/bodyprog/vw_system.h
include/game.h
src/bodyprog/bodyprog.c
src/bodyprog/view/vc_main.c
src/bodyprog/view/vc_util.c
src/bodyprog/view/vw_calc.c
src/bodyprog/view/vw_main.c
src/screens/stream/stream.c

Added `vcCamTgtMvVecIsFlipedFromCharaFront` & some savegame checksum funcs, and made clang-format closer to our formatting style.
clang-format might need some more tweaking though, would be nice if we can get it nailed down, running `git clang-format` before `git commit` would be a lot easier than manually fixing up formatting each time. (iirc some editors can also read clang-format and use formatting from it too)

bodyprog: add 4 matches, update .clang-format

---

configs/sym.bodyprog.txt
include/game.h
src/bodyprog/bodyprog_8004A87C.c
src/screens/b_konami/b_konami.c
src/screens/credits/credits.c
src/screens/saveload/saveload.c
src/screens/stream/stream.c

Both SysWork and GameWork have their own state enums, named a few values a while back but still a couple unknowns there.

Add GameState/SysState enums

---

configs/sym.bodyprog.txt
include/bodyprog/bodyprog.h
include/game.h
src/bodyprog/bodyprog.c
src/bodyprog/bodyprog_8004A87C.c
src/bodyprog/view/vc_util.c
src/screens/credits/credits.c

Started on `s_ShSaveGame`, matched a couple more savegame funcs around it, added some more gamestate inline funcs.
Seems s_GameWork has two instances of s_ShSaveGame inside, not really sure what the reason is yet though.
Also adds match for `SysState_GamePaused` state handler, but not really sure how to name it yet.

Add savegame structs & matches, GameState inline funcs.

---

include/bodyprog/bodyprog.h
include/bodyprog/math.h
include/common.h
include/game.h
include/main/rng.h
include/types.h
src/bodyprog/bodyprog.c
src/bodyprog/bodyprog_80040A64.c
src/bodyprog/view/vc_main.c
src/bodyprog/view/vc_util.c
src/bodyprog/view/vw_calc.c
src/bodyprog/view/vw_main.c
src/main/fileinfo.c
src/main/fsqueue_1.c
src/main/fsqueue_2.c
src/main/fsqueue_3.c
src/screens/stream/stream.c

- Use `TILE_UNIT()` and `FP_POS_Q` macros in place of magic numbers.
- Add `NO_VALUE` macro as a non-magic alias for invalid values (-1).
- Figure out some fields in `s_MainCharacter` and `s_SubCharacter`, mostly related to the animation system.
- General housekeeping.

Macros, fields

---

include/bodyprog/math.h
include/types.h
src/bodyprog/view/vc_main.c
src/bodyprog/view/vc_util.c
src/bodyprog/view/vw_calc.c
src/bodyprog/view/vw_main.c

- Add `TO_FIXED()` and `FROM_FIXED()` function macros for conversion to and from fixed-point Q formats.
- Add `MUL_FIXED()` function macro.
- Add `Q4_SHIFT`, `Q8_SHIFT`, and `Q12_SHIFT` constant macros for use in fixed-point conversion: Q4_SHIFT for positions, Q8_SHIFT for range limits, and Q12_SHIFT for trigonometric calculations.
- Remove `FP_POS_Q` and `FP_SIN_Q`.

Revise math macros

---

tools/objdiff/objdiff_generate.py

Updated objdiff_generate.py so that it adds these lines to objdiff.json, with that you can use `make progress` & then load project into the objdiff GUI to let it auto-build changed files for you, useful for doing local work on some small matches:
```
"build_base": true,
"custom_make": "make",
"custom_args": ["build", "NON_MATCHING=1", "SKIP_ASM=1"],
```
There is `make build-cn` which also runs `make build NON_MATCHING=1 SKIP_ASM=1` but that does a full regenerate too, maybe some `make progress-update` or `make build-progress` that just calls `build NON_MATCHING=1 SKIP_ASM=1` would be nicer.
Not sure how this might affect CI, I did see some other decomp.dev projects were using custom_make too though: https://github.com/bfbbdecomp/bfbb/blob/5ad9b58fc3586227faea9b59703e14862b80a999/tools/proj …

objdiff_generate: allow objdiff auto-build when files change

---

configs/sym.bodyprog.txt
include/bodyprog/libsd.h
src/bodyprog/libsd/sdmain.c
src/bodyprog/libsd/sdmidi.c
src/bodyprog/libsd/sdmidi2.c

Added a bunch more libsd midi funcs, started on structs but haven't really mapped much out for them yet, seems the midi stuff is all custom and not based on libsnd :(
Updated maspsx submodule to include nop fix needed for `smf_vol_set`

libsd: more midi matches, start SMF_MIDI / SMF_PORT structs

---

include/game.h
src/bodyprog/bodyprog.c
src/bodyprog/view/vc_main.c
src/bodyprog/view/vc_util.c
src/maps/map0_s00/map0_s00.c

Not really sure what happened to the structs there, changing MainCharacter to the 0x2C struct didn't seem intended but I could be wrong :P, fixed that, and looks like the NON_MATCHING in map00 matches fine now too so removed that ifdef.
There's a good chance the game didn't have any MainCharacter struct, and SysWork just has a SubCharacter field & some kind of SubModel for the extra part, seems that extra stuff is for something attached to player (gun / torch?)
I'm sure I did see some func that took in a MainCharacter* and accessed both the subchar & extra from it though, but haven't been able to dig that up again yet...

MainCharacter: struct fix

---

include/include_asm.h

Removes .endfunc defs which could mess with objdiff, `make check` etc still works fine without it.

include_asm: remove .endfunc

---

README.md
include/bodyprog/bodyprog.h
include/bodyprog/vw_system.h
include/game.h
include/maps/map0/s00.h
src/bodyprog/bodyprog_80040A64.c
src/bodyprog/view/vc_main.c
src/bodyprog/view/vw_calc.c
src/bodyprog/view/vw_main.c
src/maps/map0_s00/map0_s00.c

Matches some of the map0 funcs which seem shared between different maps, and a couple `view` funcs.
Shared funcs could probably be copied to most of the other map files (though oddly a couple do seem to be missing them), need to look into whether we could share them between them at all too.

bodyprog/map0: add 13 matches, fix some NON_MATCHING

---

tools/silentassets/extract.py

The offsets of the XA files extracted from the `HILL` archive were calculated incorrectly, using 2352 as the sector size instead of 2336, but dumpsxiso apparently strips the extra bytes from each sector when extracting the file.  
In addition,  the `blockCount` field in the filetable for XA files apparently has a different meaning (for example for videos it's the number of frames), so we can't use it to get the size of the file. Instead I made it calculate the size using the next entry's offset.  
The filenames of the XA files actually contain the size of the file: for example, `XA\C1_20670` is 20670 sectors (2336 bytes each) in size, so we can use those to get the size as an alternative.
Checked the files with jPSXdec, they seem to be correct now.

silentassets: Fix XA file extraction

---

Makefile
configs/screens/sym.stream.txt
configs/sym.bodyprog.txt
include/bodyprog/bodyprog.h
include/bodyprog/math.h
include/bodyprog/vw_system.h
include/game.h
include/screens/stream/stream.h
src/bodyprog/bodyprog.c
src/bodyprog/bodyprog_8004A87C.c
src/bodyprog/view/vc_main.c
src/screens/stream/stream.c
tools/silentassets/insertovl.py

Adds `vcInitVCSystem` `vcExecCamera` `vcAdjCamOfsAngByOfsAngSpd`, named some debug string draw funcs, and slight improvements to stream.c matches.
stream.c seems to have some leftover debug movie player code inside, but comparing with pre-Jan17 builds shows some code was removed from it at some point :(
Added some `#ifdef DEBUG` code to recreate it, but don't know if we can actually build with that yet since I'm not sure if that "MOVIE NO=" string will be inserted into rodata properly...
(commenting the line that draws "MOVIE NO" and just printing movie number does work tho, you can switch to this movie player by changing `BCCBC` to 0x11 when you're on main menu, pressing X will start playing selected movie)

view: add 3 matches, stream.c fixups, update maspsx submodule

---

configs/bodyprog.yaml
configs/main.yaml

Oops, #67 added to wrong yaml by mistake, this should let bodyprog see overlay syms properly now.

splat: add overlay syms to bodyprog instead of main

---

docs/Game Information.md

Removed columns for silentassets/shextract since we support all of them now.

docs: update release list to mention silentassets support

---

include/bodyprog/bodyprog.h
src/bodyprog/bodyprog_80085D78.c

Allows 3 funcs to match, the extern they call seems to be something in map overlay though, have a tiny part of the overlay header mapped out which I posted on discord a week or so back, but 90% of that was still unknown.

bodyprog: fix 3 NON_MATCHINGs

---

src/bodyprog/bodyprog_80040A64.c

Just had to move the `D_800C1670.field_0 = 9;` to turn 77% into 100%, weird

bodyprog: fix 1 NON_MATCHING

---

include/bodyprog/bodyprog.h
include/game.h
src/bodyprog/bodyprog_8004A87C.c

Matches 2 funcs related to Konami lightgun check, haven't added names yet but `Inventory_HyperBlasterCanAdd` / `Inventory_HyperBlasterCanUse` might fit, most of the inventory funcs seem bunched around a different address though.

bodyprog: match 2 functions

---

configs/screens/sym.b_konami.txt
configs/screens/sym.credits.txt
configs/screens/sym.options.txt
configs/screens/sym.saveload.txt
configs/screens/sym.stream.txt
configs/sym.bodyprog.txt
include/bodyprog/bodyprog.h
include/game.h
include/screens/b_konami/b_konami.h
include/screens/stream/stream.h
src/bodyprog/bodyprog.c
src/bodyprog/bodyprog_8004A87C.c
src/screens/b_konami/b_konami.c
src/screens/credits/credits.c
src/screens/options/options.c
src/screens/saveload/saveload.c
src/screens/stream/stream.c

Named each of the GameState/SysState update funcs, eg. `GameState_MainMenu_Update`, this makes the func tables look a lot nicer in .data.s file:
```
dlabel D_800A9A2C
/* 84ECC 800A9A2C 6C8F0380 */ .word SysState_Gameplay_Update
/* 84ED0 800A9A30 44930380 */ .word SysState_OptionsMenu_Update
/* 84ED4 800A9A34 68950380 */ .word SysState_StatusMenu_Update
/* 84ED8 800A9A38 D4960380 */ .word SysState_Unk3_Update
/* 84EDC 800A9A3C 589A0380 */ .word SysState_Fmv_Update
/* 84EE0 800A9A40 409C0380 */ .word SysState_LoadArea_Update
/* 84EE4 800A9A44 409C0380 */ .word SysState_LoadArea_Update
/* 84EE8 800A9A48 B89F0380 */ .word SysState_ReadMessage_Update
/* 84EEC 800A9A4C 30A20380 */ .word SysState_SaveMenu_Update
/* 84EF0 800A9A50 30A20380 */ .word SysState_SaveMenu_Update
/* 84EF4 800A9A54 …
```

symbols: add names for GameState/SysState update funcs, match `SysState_Fmv_Update`

---

Makefile
configs/bodyprog.yaml
configs/screens/b_konami.yaml
configs/sym.bodyprog.txt
include/bodyprog/bodyprog.h
include/bodyprog/vw_system.h
include/game.h
src/bodyprog/bodyprog.c
src/bodyprog/bodyprog_80085D78.c
src/bodyprog/view/vc_util.c

- Changed `s_8008A384` usages to `s_SubCharacter`
- Matched 4 `GameState_X_Update` funcs
- Added `s_MapOverlayHeader` / `g_MapOverlayHeader` symbol for map overlay data
- Adjusted splat config to ignore garbage data at end of bodyprog
- Updated makefile to include `.bin` files from asm folder
- Added weird `s_800BCE18` struct, needed for `VC_CAMERA_INTINFO` accesses to match (some funcs like func_8003CB3C / func_8003CB44 also take this as param)
- Matched `vcInitCamera`
Started on the map header struct at the beginning of each map overlay, still a lot missing from it.
Took a while to get it added properly, seems garbage data at the end of bodyprog was overlapping map overlay addr so splat wouldn't recognize symbols for it properly.
Luckily fix itself wasn't too hard, just had to set …

maps: add `g_MapOverlayHeader`, skip overlapping garbage bodyprog data, small fixups

---

include/bodyprog/bodyprog.h
include/bodyprog/math.h
include/bodyprog/vw_system.h
src/bodyprog/view/vc_util.c

Should 100% vc_util.c hopefully.
~~Maybe we should add some kind of `FP_MULTIPLY_FLOAT` to handle that weird 0x1800 multiply without needing `FP_FLOAT_TO`, not totally sure if the 1.5f value there is correct though.~~
Added that, seems fine to me.

bodyprog: match `vcMoveAndSetCamera`, finish vc_util.c, small fixups

---

include/bodyprog/bodyprog.h
include/gpu.h
include/screens/credits/credits.h
src/screens/b_konami/b_konami.c
src/screens/credits/credits.c

- Add `addPrimFast` macro to combine `addPrim` and `setlen`
- Fix non-matching in `credits`
- Add implementation of `func_801E342C`

add and fix nonmatching in credits, add addPrimFast macro

---

docs/Game Information.md
include/bodyprog/bodyprog.h
include/screens/saveload/saveload.h
src/bodyprog/bodyprog_80085D78.c

Probably a lot of other mising fn decls around too, maybe need to get gcc to output warnings for them, would help a lot on decomp.me if we had those decls ready.
Left the param names out of the decls since these funcs aren't decomped yet, seems like a good indicator for those.

bodyprog: fix 1 NON_MATCHING, add missing fn decls

---

configs/sym.bodyprog.txt
include/bodyprog/bodyprog.h
include/game.h
src/bodyprog/bodyprog.c
src/bodyprog/bodyprog_80040A64.c

Changes Unk10/11/12 to EventCallFunc / EventSetFlag / EventPlaySound
SysState_GameOver_Update needs jump table, not really sure how we add those though.
Small fixups to Sd_EngineCmd too, that func might be taking u16 param since most callers use & 0xFFFF to it, but couldn't get it to match with that changed, odd.
Contributors: @fmil95, @IWILLCRAFT-M0d

bodyprog: add SysState_EventXXX funcs, SysState_GameOver_Update

---

configs/bodyprog.yaml
include/bodyprog/bodyprog.h
include/bodyprog/vw_system.h
src/bodyprog/bodyprog_80085D78.c
src/bodyprog/view/vc_main.c

- Demo_DataRead
- Demo_JoyUpdate
- vcRetFarWatchRate
- vcSetFlagsByCamMvType
Not sure about the FP_METER uses in vcRetFarWatchRate, could be FP_ANGLE instead but not really sure how to tell.
Also have Demo_GameGlobalsRestore at https://decomp.me/scratch/ZdDtI, but it'll need sub-struct added to g_GameWork, might try adding it in soon.

bodyprog: match 4 funcs

---

include/bodyprog/bodyprog.h
include/bodyprog/math.h
src/bodyprog/view/vc_main.c
src/bodyprog/view/vc_util.c
src/bodyprog/view/vw_calc.c
src/bodyprog/view/vw_main.c
tools/maptool.py

- Changes angles to Q4.12 used in @Sparagas SH1 templates, makes most of the angle values easier to understand (eg `1.875f` -> `30.0f`, also matched float value that SH2 used)
- Small fixup to maptool/SpawnInfo to use unsigned `rotationY`, fixes wrong angle being shown.

math: switch to Q4.12 for angles, make `SpawnInfo.rotationY` unsigned

---

configs/sym.bodyprog.txt
include/bodyprog/bodyprog.h
include/bodyprog/math.h
include/bodyprog/vw_system.h
include/game.h
include/types.h
src/bodyprog/bodyprog.c
src/bodyprog/bodyprog_8004A87C.c
src/bodyprog/bodyprog_80085D78.c
src/bodyprog/view/vc_main.c
tools/maptool.py

- Rename all Q notations from ARM to TI style.
- Add two fixed-point `typedef`.
- Rename `chara_type_4` to `charaId_4`.
- Split `charaSpawnsA_24C[32]` to two `charaSpawnsA_24C[16]`, `charaSpawnsA_30C[16]` arrays.
- Remove `FP_ANGLE_COUNT` and change it to `(FP_TO(1, Q12_SHIFT))`
- Remove unused `SIN_LUT_SIZE` (if needed use `(FP_TO(1, Q12_SHIFT))` instead)
- Update `e_ShCharacterId` names.
- `_ShSaveGame`:
- Rename `field_A5` to `mapRoomIdx_A5`.
- Add description for `mapOverlayIdx_A4` and `mapIdx_A9`.
- Rename a lot of fields to `eventFlags`. -Rename a lot of fields to `mapMarkingsFlags`.
- Rename `field_25C` to `enemyKillCountPacked_25C`, but it needs to be split.
- Rename several integer values to fixed-point typedefs.
- Fix `seenGameOverTips_2E` description.
- Rename `unk_34[1]` to …

Q notations and renames

---

include/game.h
include/types.h
src/bodyprog/bodyprog_8004A87C.c

Add `q20_12` typedef and use it on `s_ShSaveGame.gameplayTimer`.
Rename `s_ShSaveGame.field_24A` to
`s_ShSaveGame.clearGameCount_24A` (max is 99)
change `s32 enemyKillCountPacked_25C` to separate values. Looks like `unknwon_25C_3` is still used, and is not padding.
Side Note:
`meleeKillCount` is a weird one. Logically it should be the same size as `rangedKillCount`. But for some reason in the RAM it can be modified as `u16`. But it can't be packed as `u16`, because the struct will we bigger with added padding.
Need more research.
Also in the future all these 4 `u8` bit field values should be packed to a struct, because it is used again in save-load screen.

Unpack `sShSaveGame.enemyKillCountPacked_25C`

---

configs/screens/saveload.yaml
include/bodyprog/bodyprog.h
include/screens/saveload/saveload.h
src/screens/saveload/saveload.c

Matches the last function from saveload. For now I'm having trouble defining the data. Somehow the padding after the D_801E2830 table gets removed when D_801E74A8 is defined. When I force the padding, another one is added.

add func_801E70C8 (Contributors: @Sezzary)

---

Dockerfile
build_image.sh
docker_run.sh

Added a Docker-based build environment to ensure consistent builds across platforms, including macOS/arm64, since the project includes `linux/amd64` binaries. The resulting Docker image is approximately 350MB in size.
- `Dockerfile`: based on `python:3.12-slim-bookworm` with all required dependencies installed
- `build_image.sh`: Builds the docker image
- `docker_run.sh`: Runs the container, mounts the project folder, and executes commands (e.g., make).
```
./build_image.sh
./docker_run.sh make setup
./docker_run.sh make
./docker_run.sh check
```

Add dockerized build

---

src/maps/map0_s00/map0_s00.c

```
make check      
mips-linux-gnu-cpp -P -MMD -MP -MT build/src/maps/map0_s00/map0_s00.i -MF build/src/maps/map0_s00/map0_s00.i.d -Iinclude -I build -Iinclude/psyq -D_LANGUAGE_C -DUSE_INCLUDE_ASM -P -MMD -MP -undef -Wall -lang-c -nostdinc -DMAP0_S00 -o build/src/maps/map0_s00/map0_s00.i src/maps/map0_s00/map0_s00.c
tools/gcc-2.8.1-psx/cc1 -O2 -G0 -mips1 -mcpu=3000 -w -funsigned-char -fpeephole -ffunction-cse -fpcc-struct-return -fcommon -fverbose-asm -msoft-float -mgas -fgnu-linker -quiet -o build/src/maps/map0_s00/map0_s00.c.s build/src/maps/map0_s00/map0_s00.i
python3 tools/maspsx/maspsx.py --aspsx-version=2.77 --run-assembler -EL -Iinclude -I build -Iinclude/psyq -O2 -G0 -march=r3000 -mtune=r3000 -no-pad-sections -o build/src/maps/map0_s00/map0_s00.c.o …
```

Matched func_800D2DAC (MAP0_S00)

---

include/screens/saveload/saveload.h
src/screens/saveload/saveload.c

Also rename `field_0` to `totalSavegameCount_0` Because it simply counts how many total saves you have on your total account and not only current playthrough.

fix bit field offsets

---

README.md
tools/objdiff/config.yaml

Removed Psy-Q decomp badge from the readme and from objdiff config, since the only Psy-Q thing remaining is the asm entrypoint code which can't be decompiled anyway.
I think having engine in its place in readme would be nicer since all the other overlays depend on that anyway, and we could see the progress for it without needing to expand it.
@IWILLCRAFT-M0d does this look fine to you? https://github.com/Vatuu/silent-hill-decomp/blob/c76b8b3e21cce387ed690269f8dcebbc5086f365/README.md
todo: need to make sure there's nothing else objdiff related which mentions Psy-Q too.
E: hm, I think the snmain.obj might still show up at https://decomp.dev/Vatuu/silent-hill-decomp?category=main after this though, not really sure how to remove that yet.

readme: replace Psy-Q with bodyprog, remove Psy-Q from objdiff

---

include/bodyprog/bodyprog.h
src/bodyprog/bodyprog_80055028.c

First contribution. Matched two small functions, `func_8005B3A4`, `func_8005D974`

Bodyprog: 2 matches

---

include/bodyprog/bodyprog.h
src/bodyprog/bodyprog_80040A64.c
src/bodyprog/bodyprog_80055028.c

Matched `func_800700F8` and `func_8004255C`. Fixed `func_8006DB3C` arguments to match the call from `func_800700F8`

Bodyprog: Matched 2 function

---

Dockerfile
requirements.txt

Use user in docker container, install some packages
Create a user with the id, group id and name of the host. This way
the files produced by this container will be owned by the user.
Otherwise all the files produced by the conainer would be owner
by root which is annoying to work with.
Install gcc (needed by permuter) and progress (needed by objdiff)
Install pycparser (needed by permuter)

Use user in docker container, install some packages

---

include/bodyprog/math.h
include/maps/shared/sharedFunc_800D3814_0_s01.h
src/maps/map0_s01/map0_s01.c
src/maps/map2_s00/map2_s00.c
src/maps/map2_s02/map2_s02.c
src/maps/map4_s02/map4_s02.c
src/maps/map5_s01/map5_s01.c
src/maps/map6_s00/map6_s00.c

@Sezzary I walked back `FP_ANGLE_TRUNCATE_ABS()` - it stopped matching when I moved it from an inline method to a define
I've replaced it with `ABS_32(x)` ...feel free to call it something else, maybe `ABS_SHIFT_32(x)` or `ABS_SHIFT(x, 32)`?
The ASM for it is just `Math_PreservedSignSubtract()` but without being a function
There are only two uses (`func_800D3814` and `func_800D4E84` of the ASM pattern but it seems too clunky to not wrap it in a macro

map0_s01: matched func_800D3814

---

configs/sym.bodyprog.txt
include/bodyprog/bodyprog.h
include/maps/map0/map0_s01.h
include/maps/shared.h
src/bodyprog/bodyprog_8003AB28.c
src/bodyprog/bodyprog_80040A64.c
src/bodyprog/bodyprog_80055028.c
src/bodyprog/view/vc_util.c

More rigged models code cleanup. Biggest change is merging s_800BCE18_0 with s_800BCE18. It's also time to give it some name. All the data in this struct is related to 3D data. MapType, models of characters and held items, models of "toggable meshes" (like item pickups, parts of the wall in the cafee). So for now let's just call it s_WorldGfx

g_WorldGfx

---

include/maps/shared.h
include/maps/shared/sharedFunc_800D8888_0_s01.h
src/maps/map0_s01/map0_s01.c
src/maps/map4_s01/map4_s01.c
src/maps/map6_s01/map6_s01.c
src/maps/map7_s03/map7_s03.c

This function is not placed in its own header like all other shared functions because different maps use a different global symbol (KAUFMAN / CYBIL _ANIM_INFOS). I think these symbols should be renamed. KAUFMAN also appeared in map0_s00 recently. I think these anim tables contain different animations on each map and we can't give a specific character name to them.

Match sharedFunc_800D8888_0_s01
