- src/main.c
https://decomp.me/scratch/wwmze
> [MAIN]: Implement func_80012110

- src/main.c
https://decomp.me/scratch/yX5RA
> [MAIN]: Implement func_8001211C

- src/main.c
https://decomp.me/scratch/WZ3yw
> [MAIN]: Implement func_8001213C

- src/main.c
https://decomp.me/scratch/UzfYT
> [MAIN]: Implement func_800120E4

- src/main.c
https://decomp.me/scratch/aRA64
> [MAIN]: Implement func_80012104

- configs/sym.bodyprog.txt
- include/bodyprog/libsd.h
- include/bodyprog/math.h
- include/bodyprog/vw_system.h
- include/common.h
- include/game.h
- include/gpu.h
- src/bodyprog/libsd/sdmain.c
- src/bodyprog/libsd/sdmidi2.c
- src/bodyprog/view/vc_main.c
- src/bodyprog/view/vc_util.c
- src/bodyprog/view/vw_calc.c
- src/bodyprog/view/vw_main.c
- src/stream/stream.c
- Reformat new pulls according to conventions.
- Add math macros to address some magic numbers.
> Formatting

- include/bodyprog/math.h
- src/bodyprog/view/vc_main.c
- src/bodyprog/view/vc_util.c
- src/bodyprog/view/vw_main.c
- Add `DEG_TO_FPA` macro for human-readable angles.
- A few raw angle conversions.
> Add DEG_TO_FPA macro

- configs/sym.bodyprog.txt
- include/bodyprog/bodyprog.h
- include/bodyprog/libsd.h
- src/bodyprog/bodyprog.c
- src/bodyprog/libsd/sdmain.c
- src/bodyprog/view/vc_main.c
Added some SdVab / SdSeq matches in libsd, and view matches thanks to @fmil95 & @1superchip.
SMF structs are mostly still unmapped, hoping it could be some standard MIDI thing but haven't found much yet.
> Add `libsd` & `view` matches

- Makefile
- src/bodyprog/bodyprog_80085D78.c
- tools/objdiff/objdiff_generate.py
~~1sec, can probably change that to the gamestate enum~~ (E: added)
> Makefile: fixup `progress`, match `func_8008F470`

- include/bodyprog/math.h
- include/bodyprog/vw_system.h
- include/game.h
- src/bodyprog/view/vc_main.c
- src/bodyprog/view/vw_calc.c
~~1 sec, small fixup~~
~~Might be able to add another one too, 1sec~~  E: added
> bodyprog: add 5 `view` matches

- include/bodyprog/bodyprog.h
- include/bodyprog/libsd.h
- include/bodyprog/math.h
- include/bodyprog/vw_system.h
- include/game.h
- include/screens/b_konami/b_konami.h
- include/screens/saveload/saveload.h
- src/bodyprog/bodyprog.c
- src/bodyprog/bodyprog_80040A64.c
- src/bodyprog/bodyprog_80085D78.c
- src/bodyprog/libsd/sdmain.c
- src/bodyprog/view/vc_main.c
- src/bodyprog/view/vw_calc.c
- src/maps/map0_s00/map0_s00.c
- src/screens/b_konami/b_konami.c
- src/screens/credits/credits.c
- src/screens/saveload/saveload.c
- src/screens/stream/stream.c
- Function matches for bodyprog
- Some matches for other overlays.
Contributors: @fgsfdsfgs, polyproxy on Discord, karas on Discord.
> Bodyprog matches

- Makefile
- configs/screens/sym.options.txt
- include/bodyprog/bodyprog.h
- include/screens/b_konami/b_konami.h
- include/screens/options/options.h
- include/screens/stream/stream.h
- src/bodyprog/bodyprog_8004A87C.c
- src/screens/options/options.c
- src/screens/stream/stream.c
- tools/updateSubmodules.sh
Thanks to @Mc-muffin and @karas84 for the matches
> Identification of functions and matches of OPTION.BIN

- docs/Coding Conventions.md
- docs/File Formats.md
- docs/Game Information.md
- docs/Organization.md
- docs/file_formats/sh1_dms.bt
Split the docs updates from #61 into separate PR, will probably add the code changes from there in a later PR.
> docs: add `File Formats.md`, `sh1_dms.bt`, release info, minor fixups

- Makefile
- requirements.txt
I hope I don't break anything ;-;
> SPLAT | Update version

- configs/sym.bodyprog.txt
- include/bodyprog/bodyprog.h
- src/bodyprog/bodyprog.c
- src/bodyprog/bodyprog_80085D78.c
- src/screens/b_konami/b_konami.c
> bodyprog: match 2 Dms funcs, add GsOUT_PACKET_P (symbols changed)

- configs/sym.bodyprog.txt
- src/bodyprog/bodyprog_80085D78.c
Thought I'd added this but guess not.
> bodyprog: match `Dms_CharacterGetPosRotByIndex` (symbols changed)

- configs/sym.bodyprog.txt
- docs/file_formats/sh1_dms.bt
- include/bodyprog/bodyprog.h
- src/bodyprog/bodyprog_80085D78.c
Fixed up some var/func/field names for DMS
> bodyprog: Dms naming fixups (symbols changed)

- configs/sym.bodyprog.txt
- docs/file_formats/sh1_dms.bt
- include/bodyprog/bodyprog.h
- src/bodyprog/bodyprog_80085D78.c
Matched `Dms_CameraKeyframeInterpolate` and 1 func that seems unused
> bodyprog: add 2 matches, KeyframeCamera field names (symbols changed)

- include/bodyprog/bodyprog.h
- src/bodyprog/bodyprog_80040A64.c
> bodyprog: progress

- include/bodyprog/bodyprog.h
- include/gpu.h
- include/screens/credits/credits.h
- src/bodyprog/bodyprog_80085D78.c
- src/screens/credits/credits.c
Adds matches:
- func_8009185C
- func_801E3970
- func_801E4394
- func_801E47E0
- func_801E4C1C
> Credits matches

- configs/sym.bodyprog.txt
- include/bodyprog/bodyprog.h
- include/bodyprog/libsd.h
- include/game.h
- src/bodyprog/bodyprog.c
- src/bodyprog/bodyprog_80040A64.c
- src/bodyprog/libsd/sdmain.c
- src/bodyprog/libsd/sdmidi.c
Some libsd matches & `SaveGame_UserConfigCopyWithChecksum` func that calcs the config struct checksum, thanks to @karas84 for helping match `SdUtKeyOffVWithRROff`.
> bodyprog: match 9 funcs, add `s_ShSaveUserConfigContainer`

- Makefile
- README.md
- include/bodyprog/libsd.h
- src/bodyprog/libsd/smf_mid.c
Added section about creating a venv, also mentions that the venv has to be activated in each terminal session.
> README: add venv setup section, 1 libsd match

- configs/screens/options.yaml
- include/bodyprog/bodyprog.h
- include/game.h
- include/screens/options/options.h
- src/bodyprog/bodyprog_80040A64.c
- src/screens/options/options.c
Adds:
- GameState_OptionScreen_Update thanks to @emoose
- Settings_ExtraScreen
- Settings_MainScreen
- Gfx_OptionsStringsExtraDraw
- Gfx_OptionsStringsMainDraw
- Gfx_SelectedOptionExtra
- Gfx_SelectedOptionMain
- Gfx_VignetteDraw
- Gfx_SettingsOptionsExtraDraw
- Gfx_SettingsOptionsMainDraw
- Gfx_LineDraw
- Gfx_ArrowDraw - with do {} while(0) workaround
- Gfx_ButtonDraw
> Adds matches to options

- configs/screens/options.yaml
- include/bodyprog/bodyprog.h
- include/screens/options/options.h
- src/screens/options/options.c
Adds:
- Gfx_PositionArrowsDraw
- Gfx_PositionIndicatorDraw
- Gfx_ControllerScreenDraw
- Gfx_ControllerButtonsDraw
> options matches

- include/bodyprog/bodyprog.h
- include/game.h
- src/bodyprog/bodyprog_80085D78.c
- src/maps/map4_s03/map4_s03.c
Contributors: @fmil95, @Sparagas, @cuckydev, @belek666, @emoose, @IWILLCRAFT-M0d
> bodyprog: match 2 funcs

- include/bodyprog/bodyprog.h
- src/bodyprog/bodyprog.c
Add a function that adds 32 to an array of a field in a struct.
> s32 func_8003BE50(s32 idx)

- configs/screens/saveload.yaml
- include/bodyprog/bodyprog.h
- include/screens/saveload/saveload.h
- src/screens/b_konami/b_konami.c
- src/screens/saveload/saveload.c
Adds `Gfx_SavesTransparentBgDraw` and `Gfx_SavesOutlineDraw` functions, fixes .rodata, and assumes a type for D_800BCD2C.
> adds saveload matches

- configs/maps/sym.map0_s00.txt
- configs/maps/sym.map0_s01.txt
- configs/maps/sym.map2_s00.txt
- configs/maps/sym.map2_s03.txt
- include/bodyprog/bodyprog.h
- include/maps/shared.h
- include/maps/shared/sharedFunc_800D92AC_0_s00.h
- src/maps/map0_s00/map0_s00_2.c
- src/maps/map0_s01/map0_s01.c
- src/maps/map2_s00/map2_s00.c
- src/maps/map2_s03/map2_s03.c
```
build/out/SLUS_007.07: OK
build/out/1ST/BODYPROG.BIN: OK
build/out/VIN/STREAM.BIN: OK
build/out/1ST/B_KONAMI.BIN: OK
build/out/VIN/STF_ROLL.BIN: OK
build/out/VIN/OPTION.BIN: OK
build/out/VIN/SAVELOAD.BIN: OK
build/out/VIN/MAP0_S00.BIN: OK
build/out/VIN/MAP0_S01.BIN: OK
build/out/VIN/MAP0_S02.BIN: OK
build/out/VIN/MAP1_S00.BIN: OK
build/out/VIN/MAP1_S01.BIN: OK
build/out/VIN/MAP1_S02.BIN: OK
build/out/VIN/MAP1_S03.BIN: OK
build/out/VIN/MAP1_S04.BIN: OK
build/out/VIN/MAP1_S05.BIN: OK
build/out/VIN/MAP1_S06.BIN: OK
build/out/VIN/MAP2_S00.BIN: OK
build/out/VIN/MAP2_S01.BIN: OK
build/out/VIN/MAP2_S02.BIN: OK
build/out/VIN/MAP2_S03.BIN: OK
build/out/VIN/MAP2_S04.BIN: OK
build/out/VIN/MAP3_S00.BIN: OK
build/out/VIN/MAP3_S01.BIN: OK
build/out/VIN/MAP3_S02.BIN: OK
build/out/VIN/MAP3_S03.BIN: …
```
> Matched sharedFunc_800D92AC_0_s00

- include/maps/map3/map3_s00.h
- src/maps/map3_s00/map3_s00.c
Added map3 matches for func_800D0960, func_800D0994, func_800D09D4
Added header for map3_s00
> Added map3 matches

- include/bodyprog/bodyprog.h
- src/bodyprog/bodyprog_80040A64.c
Matched 1 function `func_8004201C`. Also added a note in `func_800449AC`.
> Bodyprog: matched func_8004201C

- include/maps/map5/map5_s01.h
- src/maps/map5_s01/map5_s01.c
Added map5_s01 matches for func_800D2450, func_800DEF80, func_800DEFA0, func_800DEFC0, func_800DF548, func_800DF568
Added header for map5_s01
> Add matches to map5

- include/bodyprog/bodyprog.h
- include/bodyprog/math.h
- src/bodyprog/bodyprog_80040A64.c
- src/bodyprog/bodyprog_80055028.c
Matched `func_8006F338` and `func_80041BA0`
> Bodyprog: Matched 2 functions

- configs/maps/sym.map0_s01.txt
- configs/maps/sym.map0_s02.txt
- configs/maps/sym.map1_s00.txt
- configs/maps/sym.map1_s06.txt
- configs/maps/sym.map2_s00.txt
- configs/maps/sym.map2_s02.txt
- configs/maps/sym.map3_s00.txt
- configs/maps/sym.map3_s01.txt
- configs/maps/sym.map3_s06.txt
- configs/maps/sym.map5_s01.txt
- configs/maps/sym.map5_s03.txt
- configs/maps/sym.map7_s03.txt
- include/maps/shared.h
- include/maps/shared/sharedFunc_800CF2A4_0_s01.h
- include/maps/shared/sharedFunc_800CF9A8_0_s01.h
- src/maps/map0_s01/map0_s01.c
- src/maps/map0_s02/map0_s02.c
- src/maps/map1_s00/map1_s00.c
- src/maps/map1_s06/map1_s06.c
- src/maps/map2_s00/map2_s00.c
- src/maps/map2_s02/map2_s02.c
- src/maps/map3_s00/map3_s00.c
- src/maps/map3_s01/map3_s01.c
- src/maps/map3_s06/map3_s06.c
- src/maps/map5_s01/map5_s01.c
- src/maps/map5_s03/map5_s03.c
- src/maps/map7_s03/map7_s03.c
Some snow particle init/update functions
> Add shared matches for sharedFunc_800CF2A4_0_s01, sharedFunc_800CF9A8_0_s01 and sharedData_800DD796_0_s01

- include/bodyprog/bodyprog.h
- src/bodyprog/bodyprog_80040A64.c
Thanks to @pseregiet for helping debugging some problems.
> Bodyprog: Matched func_800421D8

- configs/maps/sym.map0_s01.txt
- configs/maps/sym.map0_s02.txt
- configs/maps/sym.map1_s00.txt
- configs/maps/sym.map2_s00.txt
- configs/maps/sym.map2_s02.txt
- configs/maps/sym.map3_s00.txt
- configs/maps/sym.map3_s01.txt
- configs/maps/sym.map3_s06.txt
- configs/maps/sym.map5_s01.txt
- configs/maps/sym.map5_s03.txt
- include/maps/shared.h
- include/maps/shared/sharedFunc_800CE59C_0_s01.h
- src/maps/map0_s01/map0_s01.c
- src/maps/map0_s02/map0_s02.c
- src/maps/map1_s00/map1_s00.c
- src/maps/map2_s00/map2_s00.c
- src/maps/map2_s02/map2_s02.c
- src/maps/map3_s00/map3_s00.c
- src/maps/map3_s01/map3_s01.c
- src/maps/map3_s06/map3_s06.c
- src/maps/map5_s01/map5_s01.c
- src/maps/map5_s03/map5_s03.c
Thanks to belek666 & Loud Quetzal for match help
> Match func_800CE59C

- include/bodyprog/bodyprog.h
- src/bodyprog/bodyprog_80054FC0.c
Thanks to @fmil95 for help on matching.
> Bodyprog: Matched func_8006B9C8

- include/bodyprog/bodyprog.h
- include/game.h
- src/bodyprog/bodyprog_80085D78.c
Thanks to @polybiusproxy for the help.
> Bodyprog: Matched func_8008A0E4

- include/bodyprog/bodyprog.h
- src/bodyprog/bodyprog_80040A64.c
Thanks to @fmil95 for the help.
> Bodyprog: Matched func_80043A24

- configs/maps/sym.map0_s01.txt
- include/bodyprog/math.h
- include/maps/map0/map0_s01.h
- src/maps/map0_s01/map0_s01_events.c
Thanks to emoose for inline function trick.
> Deobfuscate func_800DC9C8

- configs/maps/map0_s01.yaml
- configs/maps/sym.map0_s01.txt
- include/bodyprog/bodyprog.h
- include/maps/map0/map0_s01.h
- src/bodyprog/bodyprog_80032D1C.c
- src/bodyprog/bodyprog_80085D78.c
- src/maps/map0_s01/map0_s01_events.c
- src/maps/map0_s01/map0_s01_msg.c
https://decomp.me/scratch/P0BOs
> func_800DA98

- src/maps/map0_s01/map0_s01.c
https://decomp.me/scratch/ugKyK
> func_800D3DFC

- include/game.h
- src/maps/map0_s01/map0_s01.c
https://decomp.me/scratch/FDEh8 thx @Giragast
> func_800D71F0

- include/bodyprog/bodyprog.h
- include/game.h
- src/bodyprog/bodyprog_80054FC0.c
- src/bodyprog/bodyprog_80085D78.c
Matched `func_8005E70C`, `func_80089524`, `func_8006DA08` and `func_8006DC18`
> Bodyprog: Matched 4 functions

- include/bodyprog/bodyprog.h
- src/bodyprog/bodyprog_80040A64.c
- src/bodyprog/bodyprog_80055028.c
`func_80043554`, `func_8006DAE4`, `func_8006D774`, `func_800452EC`, `func_8006C3D4`
> Bodyprog: Matched 5 small functions

- include/bodyprog/bodyprog.h
- src/bodyprog/bodyprog_8003AB28.c
- src/bodyprog/bodyprog_80040A64.c
This PR fixes the layout of several structures and the functions that use them. One thing that I am uncertain of is bones_4 field in s_Skeleton. We already have a bones array in this structure. Maybe it's used to build a hierarchy of bones.
> s_Bone, s_Skeleton, s_800BCE18_0_CC, s_800BCE18_0 fixup

- include/maps/map0/map0_s00.h
- src/maps/map0_s00/map0_s00.c
thanks again to @fgsfds and @belek666 for the help with a match.
> MAP0_S00: match func_800D0394

- include/maps/map0/map0_s00.h
- src/maps/map0_s00/map0_s00.c
thx @emoose and @Giragast for the help with a match.
> MAP0_S00: match func_800CC6E8
